# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currently', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='link',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='link',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
