# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currently', '0002_auto_20160308_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
